apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "list-keep-chart.fullname" . }}
  labels:
    {{- include "list-keep-chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "list-keep-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "list-keep-chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "list-keep-chart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: ACCESS_LOG
              value: "-"
            - name: DATABASE_URL
              value: mysql+pymysql://ctfd:1a6TOt0j92kv@mariadb-master-0.mariadb-master.default.svc.cluster.local/ctfd
            - name: ERROR_LOG
              value: "-"
            - name: LOG_FOLDER
              value: /var/log/CTFd
            - name: REDIS_URL
              value: redis://default:f9kMsqbWtkYVywzlcp70FJT74ecJWxNn@redis-17545.c245.us-east-1-3.ec2.cloud.redislabs.com:17545
            - name: REVERSE_PROXY
              value: "true"
            - name: UPLOAD_FOLDER
              value: /var/uploads
            - name: WORKERS
              value: "1"

          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          #livenessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          #readinessProbe:
          #  httpGet:
          #    path: /
          #    port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
